export const GET_LIST = 'getList'
export const SET_LIST = 'setList'
export const SET_ACTIVE = 'setActive'
export const PUSH_DATA = 'pushData'
export const CREATE_DATA = 'createData'
export const SET_MSG = 'setMsg'
export const SET_MORE = 'setMore'
export const UPDATE_DATA = 'updateData'
export const SET_CLIP_BOARD = 'setClipBoard'
export const SET_ACTION_TYPE = 'setActionType'
export const BIND_FILE = 'bindFile'
export const BIND_ASSET = 'bindAsset'
export const GET_INFO = 'getInfo'

export const REMOVE_DATA = 'removeData'
export const DETACH_DATA = 'detachData'
export const UPLOAD_DATA = 'uploadData'
export const REUPLOAD_DATA = 'reUploadData'
export const CLIP_BOARD = 'clipBoard'

export const SET_FETCHING = 'setFetching'
export const SET_LOADING = 'setLoading'
export const SET_UPLOAD_PROGRESS = 'setUploadProgress'
export const SET_DOWNLOAD_PROGRESS = 'setDownloadProgress'

export const VERIFICATION_CODES = 'verificationCodes'
export const VERIFICATION_CODE_STORE = 'verificationCodeStore'
export const VERIFICATION_CODE_AUTHENTICATION = 'verificationCodeAuthentication'
export const AUTHENTICATION = 'authorizations'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
